import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const categories = ['All', 'Culture', 'Workshop', 'Sports', 'Talk']
const blankEvent = { title: '', category: 'Workshop', date: '', time: '', venue: '', description: '', featured: false, color: 'blue' }
const api = async (path, options = {}) => {
  const response = await fetch(`/api${path}`, { headers: { 'Content-Type': 'application/json' }, ...options })
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).message || 'Something went wrong.')
  return response.status === 204 ? null : response.json()
}
const formatDate = date => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T12:00:00`))
const Icon = ({ name }) => <span className={`icon icon-${name}`} aria-hidden="true" />

function EventCard({ event, onRegister, onEdit, onDelete, admin = false }) {
  return <article className={`event-card tint-${event.color}`}>
    <div className="event-card-top"><span className="pill">{event.category}</span>{event.featured && <span className="star">★ Featured</span>}</div>
    <h3>{event.title}</h3><p className="event-description">{event.description}</p>
    <div className="event-meta"><span><Icon name="calendar" />{formatDate(event.date)}</span><span><Icon name="clock" />{event.time}</span><span><Icon name="pin" />{event.venue}</span></div>
    {admin ? <div className="card-actions"><button className="text-button" onClick={() => onEdit(event)}>Edit</button><button className="text-button danger" onClick={() => onDelete(event.id)}>Delete</button></div> : <button className="register-button" onClick={() => onRegister(event)}>Save your spot <span>→</span></button>}
  </article>
}

function Modal({ children, onClose }) { return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e => e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button>{children}</section></div> }

function RegistrationModal({ event, onClose, onDone }) {
  const [form, setForm] = useState({ name: '', email: '', collegeYear: '', phone: '' }); const [error, setError] = useState(''); const [sending, setSending] = useState(false)
  const submit = async e => { e.preventDefault(); setSending(true); setError(''); try { await api('/registrations', { method: 'POST', body: JSON.stringify({ ...form, eventId: event.id }) }); onDone(`You're registered for ${event.title}!`) } catch (err) { setError(err.message); setSending(false) } }
  return <Modal onClose={onClose}><div className="modal-heading"><span className="eyebrow">EVENT REGISTRATION</span><h2>Save your spot</h2><p>{event.title} · {formatDate(event.date)}</p></div><form className="form-grid" onSubmit={submit}>{[['name','Your name'],['email','College email'],['collegeYear','College / year'],['phone','Phone number']].map(([key,label]) => <label key={key}>{label}<input type={key === 'email' ? 'email' : 'text'} value={form[key]} onChange={e => setForm({...form,[key]:e.target.value})} required /></label>)}{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={sending}>{sending ? 'Registering...' : 'Complete registration →'}</button></form></Modal>
}

function EventForm({ initial, onSave, onClose }) {
  const [form, setForm] = useState(initial || blankEvent); const [error, setError] = useState(''); const edit = Boolean(initial)
  const change = e => setForm({ ...form, [e.target.name]: e.target.type === 'checkbox' ? e.target.checked : e.target.value })
  const submit = async e => { e.preventDefault(); setError(''); try { await onSave(form) } catch (err) { setError(err.message) } }
  return <Modal onClose={onClose}><div className="modal-heading"><span className="eyebrow">ADMIN PANEL</span><h2>{edit ? 'Edit event' : 'Create an event'}</h2></div><form className="form-grid event-form" onSubmit={submit}><label>Event name<input name="title" value={form.title} onChange={change} required /></label><div className="form-row"><label>Category<select name="category" value={form.category} onChange={change}>{categories.slice(1).map(x => <option key={x}>{x}</option>)}</select></label><label>Accent<select name="color" value={form.color} onChange={change}>{['blue','violet','orange','pink','green'].map(x => <option key={x}>{x}</option>)}</select></label></div><div className="form-row"><label>Date<input name="date" type="date" value={form.date} onChange={change} required /></label><label>Time<input name="time" type="time" value={form.time} onChange={change} required /></label></div><label>Venue<input name="venue" value={form.venue} onChange={change} required /></label><label>Description<textarea name="description" value={form.description} onChange={change} required /></label><label className="checkbox"><input name="featured" type="checkbox" checked={form.featured} onChange={change} /> Make this the featured event</label>{error && <p className="form-error">{error}</p>}<button className="primary-button">{edit ? 'Save changes' : 'Publish event'}</button></form></Modal>
}

function App() {
  const [events, setEvents] = useState([]); const [registrations, setRegistrations] = useState([]); const [page, setPage] = useState('home'); const [filter, setFilter] = useState('All'); const [search, setSearch] = useState(''); const [registering, setRegistering] = useState(null); const [editing, setEditing] = useState(undefined); const [toast, setToast] = useState(''); const [loading, setLoading] = useState(true); const [adminSearch, setAdminSearch] = useState('')
  const load = async () => { try { const [eventData, regData] = await Promise.all([api('/events'), api('/registrations')]); setEvents(eventData); setRegistrations(regData) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const notify = message => { setRegistering(null); setToast(message); load(); setTimeout(() => setToast(''), 3500) }
  const visible = useMemo(() => events.filter(event => (filter === 'All' || event.category === filter) && event.title.toLowerCase().includes(search.toLowerCase())), [events, filter, search])
  const eventSave = async data => { await api(editing?.id ? `/events/${editing.id}` : '/events', { method: editing?.id ? 'PUT' : 'POST', body: JSON.stringify(data) }); setEditing(undefined); notify(editing?.id ? 'Event updated.' : 'Event published.') }
  const eventDelete = async id => { if (!window.confirm('Delete this event and its registrations?')) return; await api(`/events/${id}`, { method: 'DELETE' }); notify('Event deleted.') }
  const featured = events.find(event => event.featured) || events[0]
  const nav = target => { setPage(target); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  if (loading) return <main className="loading">Loading campus life…</main>
  return <><header><button className="brand" onClick={() => nav('home')}><span>cc</span> CLUB CONNECT</button><nav><button className={page === 'home' ? 'active' : ''} onClick={() => nav('home')}>Home</button><button className={page === 'events' ? 'active' : ''} onClick={() => nav('events')}>Events</button><button className={page === 'admin' ? 'active' : ''} onClick={() => nav('admin')}>Admin</button></nav><button className="nav-cta" onClick={() => nav('events')}>Explore events <span>→</span></button></header>
  {page === 'home' && <main><section className="hero"><div className="hero-copy"><span className="eyebrow">YOUR CAMPUS, IN MOTION</span><h1>Find your <em>people.</em><br />Make a memory.</h1><p>From ideas that spark at workshops to nights that echo long after the music stops — this is where campus comes alive.</p><div className="hero-actions"><button className="primary-button" onClick={() => nav('events')}>Discover events <span>→</span></button><button className="play-button" onClick={() => document.querySelector('#clubs')?.scrollIntoView({behavior:'smooth'})}>↓ <span>Meet the clubs</span></button></div></div><div className="hero-art"><div className="sun" /><div className="arch"><span>MAKE<br />SOMETHING<br />MATTER.</span></div><div className="scribble">✦</div><div className="hero-note">OCT<br /><b>18</b></div></div></section><section id="clubs" className="intro"><span className="eyebrow">A PLACE TO BELONG</span><div><h2>One campus.<br /><em>Infinite ways</em> to show up.</h2><p>Club Connect brings every student community into one vibrant space. Try something new, find your team, or finally join the club you keep hearing about.</p></div><div className="club-stat"><b>18</b><span>student-led<br />clubs & societies</span></div></section>{featured && <section className="featured"><div className={`featured-visual tint-${featured.color}`}><span>FEATURED<br />EVENT</span><div className="large-star">✦</div></div><div className="featured-copy"><span className="eyebrow">DON'T MISS THIS</span><h2>{featured.title}</h2><p>{featured.description}</p><div className="featured-details"><span><Icon name="calendar" /> {formatDate(featured.date)} · {featured.time}</span><span><Icon name="pin" /> {featured.venue}</span></div><button className="primary-button" onClick={() => setRegistering(featured)}>Reserve your spot <span>→</span></button></div></section>}<section className="upcoming"><div className="section-heading"><div><span className="eyebrow">WHAT'S HAPPENING</span><h2>Coming up next</h2></div><button className="link-button" onClick={() => nav('events')}>See all events →</button></div><div className="card-grid">{events.filter(event => !event.featured).slice(0,3).map(event => <EventCard key={event.id} event={event} onRegister={setRegistering} />)}</div></section></main>}
  {page === 'events' && <main className="events-page"><div className="page-title"><span className="eyebrow">FIND YOUR NEXT THING</span><h1>All <em>events.</em></h1><p>A campus full of good ideas, good energy and good company.</p></div><div className="event-controls"><label className="search"><Icon name="search" /><input placeholder="Search events" value={search} onChange={e => setSearch(e.target.value)} /></label><div className="filters">{categories.map(category => <button key={category} onClick={() => setFilter(category)} className={filter === category ? 'selected' : ''}>{category}</button>)}</div></div><p className="result-count">{visible.length} event{visible.length !== 1 ? 's' : ''} waiting for you</p><div className="card-grid">{visible.map(event => <EventCard key={event.id} event={event} onRegister={setRegistering} />)}</div></main>}
  {page === 'admin' && <main className="admin-page"><div className="admin-header"><div><span className="eyebrow">CLUB CONNECT ADMIN</span><h1>Keep campus <em>moving.</em></h1><p>Manage events and see who's joining in.</p></div><button className="primary-button" onClick={() => setEditing(null)}>+ Add event</button></div><div className="dashboard-stats"><div><b>{events.length}</b><span>Live events</span></div><div><b>{registrations.length}</b><span>Total registrations</span></div><div><b>{new Set(registrations.map(item => item.eventId)).size}</b><span>Events with sign-ups</span></div></div><section className="admin-section"><div className="section-heading"><h2>Events</h2><span>{events.length} total</span></div><div className="admin-event-list">{events.map(event => <EventCard key={event.id} event={event} admin onEdit={setEditing} onDelete={eventDelete} />)}</div></section><section className="admin-section"><div className="section-heading"><div><h2>Student registrations</h2><span>{registrations.length} total</span></div><label className="search compact"><Icon name="search" /><input placeholder="Search name, email or event" value={adminSearch} onChange={e => setAdminSearch(e.target.value)} /></label></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Event</th><th>College / Year</th><th>Phone</th><th>Registered</th></tr></thead><tbody>{registrations.filter(item => `${item.name} ${item.email} ${item.event}`.toLowerCase().includes(adminSearch.toLowerCase())).map(item => <tr key={item.id}><td><b>{item.name}</b><small>{item.email}</small></td><td>{item.event}</td><td>{item.collegeYear}</td><td>{item.phone}</td><td>{new Date(item.createdAt).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div></section></main>}
  <footer><button className="brand" onClick={() => nav('home')}><span>cc</span> CLUB CONNECT</button><p>Made for the moments between classes.</p><span>© 2026 Campus Life</span></footer>{registering && <RegistrationModal event={registering} onClose={() => setRegistering(null)} onDone={notify} />}{editing !== undefined && <EventForm initial={editing} onClose={() => setEditing(undefined)} onSave={eventSave} />}{toast && <div className="toast">✓ {toast}</div>}</>
}

createRoot(document.getElementById('root')).render(<App />)
